/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DailyLog = IDL.Record({
  'id' : IDL.Text,
  'labourCount' : IDL.Nat,
  'date' : IDL.Text,
  'siteId' : IDL.Text,
  'photoBlobIds' : IDL.Vec(IDL.Text),
  'workDone' : IDL.Text,
  'materialExpense' : IDL.Nat,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'uploadedDate' : IDL.Text,
  'name' : IDL.Text,
  'blobId' : IDL.Text,
  'siteId' : IDL.Text,
});
export const PaymentEntry = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'siteId' : IDL.Text,
  'amountReceived' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Site = IDL.Record({
  'id' : IDL.Text,
  'totalContractValue' : IDL.Nat,
  'clientName' : IDL.Text,
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'companyName' : IDL.Opt(IDL.Text),
});
export const SiteAggregate = IDL.Record({
  'totalReceived' : IDL.Nat,
  'profitLoss' : IDL.Int,
  'totalExpense' : IDL.Nat,
  'pendingAmount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyLog' : IDL.Func([IDL.Text, DailyLog], [], []),
  'addDocument' : IDL.Func([IDL.Text, Document], [], []),
  'addPaymentEntry' : IDL.Func([IDL.Text, PaymentEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSite' : IDL.Func([IDL.Text, Site], [], []),
  'deleteDailyLog' : IDL.Func([IDL.Text], [], []),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'deletePaymentEntry' : IDL.Func([IDL.Text], [], []),
  'deleteSite' : IDL.Func([IDL.Text], [], []),
  'getAllSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyLog' : IDL.Func([IDL.Text], [DailyLog], ['query']),
  'getDailyLogsForSite' : IDL.Func([IDL.Text], [IDL.Vec(DailyLog)], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
  'getDocumentsForSite' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
  'getPaymentEntriesForSite' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentEntry)],
      ['query'],
    ),
  'getPaymentEntry' : IDL.Func([IDL.Text], [PaymentEntry], ['query']),
  'getSite' : IDL.Func([IDL.Text], [Site], ['query']),
  'getSiteAggregates' : IDL.Func([IDL.Text], [SiteAggregate], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDailyLog' : IDL.Func([IDL.Text, DailyLog], [], []),
  'updatePaymentEntry' : IDL.Func([IDL.Text, PaymentEntry], [], []),
  'updateSite' : IDL.Func([IDL.Text, Site], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DailyLog = IDL.Record({
    'id' : IDL.Text,
    'labourCount' : IDL.Nat,
    'date' : IDL.Text,
    'siteId' : IDL.Text,
    'photoBlobIds' : IDL.Vec(IDL.Text),
    'workDone' : IDL.Text,
    'materialExpense' : IDL.Nat,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'uploadedDate' : IDL.Text,
    'name' : IDL.Text,
    'blobId' : IDL.Text,
    'siteId' : IDL.Text,
  });
  const PaymentEntry = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'siteId' : IDL.Text,
    'amountReceived' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Site = IDL.Record({
    'id' : IDL.Text,
    'totalContractValue' : IDL.Nat,
    'clientName' : IDL.Text,
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'companyName' : IDL.Opt(IDL.Text),
  });
  const SiteAggregate = IDL.Record({
    'totalReceived' : IDL.Nat,
    'profitLoss' : IDL.Int,
    'totalExpense' : IDL.Nat,
    'pendingAmount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyLog' : IDL.Func([IDL.Text, DailyLog], [], []),
    'addDocument' : IDL.Func([IDL.Text, Document], [], []),
    'addPaymentEntry' : IDL.Func([IDL.Text, PaymentEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSite' : IDL.Func([IDL.Text, Site], [], []),
    'deleteDailyLog' : IDL.Func([IDL.Text], [], []),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'deletePaymentEntry' : IDL.Func([IDL.Text], [], []),
    'deleteSite' : IDL.Func([IDL.Text], [], []),
    'getAllSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyLog' : IDL.Func([IDL.Text], [DailyLog], ['query']),
    'getDailyLogsForSite' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyLog)],
        ['query'],
      ),
    'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
    'getDocumentsForSite' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getPaymentEntriesForSite' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentEntry)],
        ['query'],
      ),
    'getPaymentEntry' : IDL.Func([IDL.Text], [PaymentEntry], ['query']),
    'getSite' : IDL.Func([IDL.Text], [Site], ['query']),
    'getSiteAggregates' : IDL.Func([IDL.Text], [SiteAggregate], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDailyLog' : IDL.Func([IDL.Text, DailyLog], [], []),
    'updatePaymentEntry' : IDL.Func([IDL.Text, PaymentEntry], [], []),
    'updateSite' : IDL.Func([IDL.Text, Site], [], []),
  });
};

export const init = ({ IDL }) => { return []; };