/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyLog {
  'id' : string,
  'labourCount' : bigint,
  'date' : string,
  'siteId' : string,
  'photoBlobIds' : Array<string>,
  'workDone' : string,
  'materialExpense' : bigint,
}
export interface Document {
  'id' : string,
  'uploadedDate' : string,
  'name' : string,
  'blobId' : string,
  'siteId' : string,
}
export interface PaymentEntry {
  'id' : string,
  'date' : string,
  'notes' : string,
  'siteId' : string,
  'amountReceived' : bigint,
}
export interface Site {
  'id' : string,
  'totalContractValue' : bigint,
  'clientName' : string,
  'name' : string,
  'user' : Principal,
  'location' : string,
  'startDate' : string,
}
export interface SiteAggregate {
  'totalReceived' : bigint,
  'profitLoss' : bigint,
  'totalExpense' : bigint,
  'pendingAmount' : bigint,
}
export interface UserProfile { 'name' : string, 'companyName' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyLog' : ActorMethod<[string, DailyLog], undefined>,
  'addDocument' : ActorMethod<[string, Document], undefined>,
  'addPaymentEntry' : ActorMethod<[string, PaymentEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSite' : ActorMethod<[string, Site], undefined>,
  'deleteDailyLog' : ActorMethod<[string], undefined>,
  'deleteDocument' : ActorMethod<[string], undefined>,
  'deletePaymentEntry' : ActorMethod<[string], undefined>,
  'deleteSite' : ActorMethod<[string], undefined>,
  'getAllSites' : ActorMethod<[], Array<Site>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyLog' : ActorMethod<[string], DailyLog>,
  'getDailyLogsForSite' : ActorMethod<[string], Array<DailyLog>>,
  'getDocument' : ActorMethod<[string], Document>,
  'getDocumentsForSite' : ActorMethod<[string], Array<Document>>,
  'getPaymentEntriesForSite' : ActorMethod<[string], Array<PaymentEntry>>,
  'getPaymentEntry' : ActorMethod<[string], PaymentEntry>,
  'getSite' : ActorMethod<[string], Site>,
  'getSiteAggregates' : ActorMethod<[string], SiteAggregate>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDailyLog' : ActorMethod<[string, DailyLog], undefined>,
  'updatePaymentEntry' : ActorMethod<[string, PaymentEntry], undefined>,
  'updateSite' : ActorMethod<[string, Site], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];